### PR TITLE
Fixed a bug for video without nb_frames inference_realesrgan_video.py

### PR DESCRIPTION
**Pull request by BenjiKCF**
Fixed a bug for video without nb_frames

### CODE REVIEW

**Comment by xinntao** [comment]
It seems that the pylint is not passed
image

Can you fix it ?

**Review by BenjiKCF — COMMENTED** [review]
Updated to pass pylint test

**Comment by BenjiKCF** [comment]
> It seems that the pylint is not passed image
> 
> Can you fix it ?

Yes, I think I’ve fixed it.

**Comment by krausedj** [comment]
i did a merge with this today and converted a file missing nb_frames successfully.

**Comment by Justieku** [comment]
ret['nb_frames'] = int(video_streams[0]['nb_frames'])
KeyError: 'nb_frames'
[vost#0:0/rawvideo @ 0x557e1b9f6740] Error submitting a packet to the muxer: Broken pipe
    Last message repeated 1 times
[out#0/rawvideo @ 0x557e1b991840] Error muxing a packet
[out#0/rawvideo @ 0x557e1b991840] Task finished with error code: -32 (Broken pipe)
[out#0/rawvideo @ 0x557e1b991840] Terminating thread with return code -32 (Broken pipe)
[out#0/rawvideo @ 0x557e1b991840] Error writing trailer: Broken pipe
[out#0/rawvideo @ 0x557e1b991840] Error closing file: Broken pipe

**Pull request closed without merging**
